---
title: "Report for `r params$display_filename`"
date:  "`r format(Sys.Date(), '%B %d, %Y')`"

# Smaller HTML but uglier, see
# https://bookdown.org/yihui/rmarkdown/r-package-vignette.html
# output: rmarkdown::html_vignette

# Larger file (600kb) but prettier
output:  html_document

params:
  filename: 'missing-filename'
  display_filename: ''
---

```{r setup, include=FALSE,echo=FALSE}
library(NanoStringQCPro)
library(knitr)
#Example data from the NanoStringQCPro package:
#filename = system.file("extdata", "RCC",
#                           "20140604_C3-stim_C3-stim_11.RCC",
#                           package="NanoStringQCPro")
data = readRcc(params$filename)
x = data$Code_Summary
```


### Number of Genes Found
```{r echo=FALSE}
x$Count = as.integer(x$Count)
num_genes_per_class = table(x$CodeClass)
barplot(num_genes_per_class, col=c("red","green","blue","yellow"))
```

### Number of Gene-Counts Found

```{r echo=FALSE}
counts_per_class = tapply(x$Count, x$CodeClass, sum)
barplot(counts_per_class, col=c("red","green","blue","yellow"))
```

## Data

```{r, echo=FALSE}
kable(x)
```
