# Generated by Django 3.2.10 on 2022-01-07 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('transplants', '0001_initial'), ('transplants', '0002_auto_20211222_1425'), ('transplants', '0003_auto_20220104_1150'), ('transplants', '0004_auto_20220105_0953'), ('transplants', '0005_alter_fileupload_batch')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transplant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transplant_date', models.DateField()),
                ('donor_ref', models.CharField(max_length=256)),
                ('recipient_ref', models.CharField(max_length=256)),
                ('donor_record_date', models.DateField()),
                ('donor_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('recipient_record_date', models.DateField()),
                ('pre_transplant_dialysis', models.BooleanField(blank=True, null=True)),
                ('time_on_dialysis', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transplant_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transplant_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biopsy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biopsy_date', models.DateField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biopsy_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biopsy_modified', to=settings.AUTH_USER_MODEL)),
                ('transplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transplants.transplant')),
            ],
            options={
                'verbose_name_plural': 'biopsies',
            },
        ),
        migrations.CreateModel(
            name='Histology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('histology_date', models.DateField()),
                ('biopsy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transplants.biopsy')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histology_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histology_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'histologies',
            },
        ),
        migrations.CreateModel(
            name='FileUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileuploadbatch_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileuploadbatch_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'file upload batches',
            },
        ),
        migrations.CreateModel(
            name='SequencingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencing_date', models.DateField()),
                ('biopsy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transplants.biopsy')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencingdata_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequencingdata_modified', to=settings.AUTH_USER_MODEL)),
                ('file_path', models.FileField(editable=False, null=True, upload_to='')),
                ('file_ref', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'sequencing data',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_ref', models.CharField(max_length=256)),
                ('file_path', models.FileField(upload_to='')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='transplants.fileuploadbatch')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileupload_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileupload_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
