# Generated by Django 3.2.10 on 2022-01-19 06:26

import bhot.transplants.models.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0001_squashed_0005_alter_fileupload_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_path',
            field=models.FileField(upload_to=bhot.transplants.models.file_upload.RandomFileName('upload')),
        ),
    ]
