# Generated by Django 3.2.10 on 2021-12-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transplant',
            name='donor_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transplant',
            name='pre_transplant_dialysis',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transplant',
            name='time_on_dialysis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
