# Generated by Django 3.2.10 on 2022-01-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0002_alter_fileupload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='transplant',
            name='donor_criteria',
            field=models.CharField(blank=True, choices=[('SCD', 'Standard Donor Criteria'), ('ECD', 'Expanded Donor Criteria')], max_length=100),
        ),
    ]
