# Generated by Django 3.2.10 on 2022-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0002_alter_fileupload_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsy',
            name='proteinuria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='proteinuria_unit',
            field=models.CharField(choices=[('g/g', 'g/g'), ('g/24h', 'g/24h'), ('g/L', 'g/L'), ('mg/mmol', 'mg/mmol'), ('g/mmol', 'g/mmol')], default='mg/mmol', max_length=32),
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='file_ref',
            field=models.CharField(blank=True, help_text='<b>This must be set if you want to add a file.</b><br/>This reference will be matched against files that are uploaded as batches.<br/>You can also upload a file directly and it will be associated to this reference.', max_length=256),
        ),
    ]
