# Generated by Django 3.2.10 on 2022-01-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0003_auto_20220104_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileuploadbatch',
            options={'verbose_name_plural': 'file upload batches'},
        ),
        migrations.AddField(
            model_name='sequencingdata',
            name='file_path',
            field=models.FileField(editable=False, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sequencingdata',
            name='file_ref',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
