# Generated by Django 3.2.10 on 2022-01-05 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0004_auto_20220105_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='transplants.fileuploadbatch'),
        ),
    ]
