# Generated by Django 3.2.10 on 2022-01-19 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0004_transplant_donor_egfr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transplant',
            name='donor_egfr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Donor eGFR (mL/min/1.73m2)'),
        ),
    ]
