# Generated by Django 3.2.10 on 2022-02-23 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplants', '0005_alter_transplant_donor_egfr'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsy',
            name='ah_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_bkv_load',
            field=models.IntegerField(blank=True, null=True, verbose_name='BKV load (copies/mL)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_cmv_load',
            field=models.IntegerField(blank=True, null=True, verbose_name='CMV load (copies/mL)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_creatinemia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_creatinemia_units',
            field=models.CharField(choices=[('mg/dL', 'mg/dL'), ('umol/L', 'umol/L')], default='mg/dL', max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_creatinuria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_creatinuria_units',
            field=models.CharField(choices=[('umol/L', 'umol/L')], default='umol/L', max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_dd_cf_dna',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Donor-derived cf-DNA (%)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_ebv_load',
            field=models.IntegerField(blank=True, null=True, verbose_name='EBV load (copies/mL)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_immunosuppressant_c0',
            field=models.FloatField(blank=True, null=True, verbose_name='immunosuppressant postdose level: C2 (ng/mL)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_immunosuppressants',
            field=models.CharField(blank=True, choices=[('Abatacept', 'Abatacept'), ('Azathioprine', 'Azathioprine'), ('Belatacept', 'Belatacept'), ('Cyclosporine', 'Cyclosporine'), ('Everolimus', 'Everolimus'), ('MMF', 'MMF'), ('MPA', 'MPA'), ('Prednisone', 'Sirolimus'), ('Sirolimus', 'Azathioprine'), ('Tacrolimus', 'Tacrolimus')], max_length=100, verbose_name='Immunosuppresants'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_indication',
            field=models.CharField(blank=True, choices=[('protocol', 'protocol'), ('DGF', 'Delayed Graft Function'), ('Slow deterioration', 'Slow deterioration (progressive increase in serum creatinine over time)'), ('ARF', 'Acute renal failure'), ('Proteinuria', 'Proteinuria'), ('Hematuria', 'Hematuria'), ('SAR', 'Suspicious for acute rejection'), ('SPVN', 'Suspicious for Polyoma Virus Nephropathy'), ('Transplantectomy', 'Transplantectomy biopsy'), ('de novo DSA', 'de novo DSA'), ('Follow-up', 'Follow-up from previous biopsy')], max_length=100),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_prot_creat_ratio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)], verbose_name='Protein/creatinine ratio (g/g)'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_prot_creat_ratio_units',
            field=models.CharField(choices=[('g/g', 'g/g')], default='g/g', max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_proteinuria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_proteinuria_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_proteinuria_dipstick',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_proteinuria_dipstick_units',
            field=models.CharField(choices=[('mg/dL range', 'mg/dL range')], default='mg/dL range', max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_proteinuria_units',
            field=models.CharField(choices=[('g/g', 'g/g'), ('g/24h', 'g/24h'), ('mg/dL', 'mg/dL'), ('g/L', 'g/L'), ('mg/mmol', 'mg/mmol'), ('g/mmol', 'g/mmol')], default='mg/dL', max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_rejection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_rejection_treatment',
            field=models.CharField(blank=True, choices=[('Alemtuzumab', 'Alemtuzumab'), ('Bortezomib', 'Bortezomib'), ('Anti-thymocyte globulin', 'Anti-thymocyte globulin'), ('Eculizimab', 'Eculizimab'), ('IVIG', 'IVIG'), ('Plasmapharesis', 'Plasmapharesis'), ('Rituximab', 'Rituximab')], max_length=100, verbose_name='rejection treatment'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_treatment_response',
            field=models.CharField(blank=True, choices=[('Complete response', 'Complete response (Cr within 10% of baseline)'), ('Partial response', 'Partial response (Cr 10-50% over baseline) '), ('No response', 'No response (Cr >50% increase over baseline)')], max_length=100, verbose_name='Rejection treatment response'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_treatment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='biopsy_type',
            field=models.CharField(blank=True, choices=[('procurement', 'procurement'), ('pre-implantation', 'pre-implantation')], max_length=100),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='c1q_binding',
            field=models.BooleanField(blank=True, null=True, verbose_name='C1q binding'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='ci_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=100),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='ct_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='cv_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='dsa_at_biopsy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='graft_failure_cause',
            field=models.CharField(blank=True, choices=[('death', 'death'), ('infection', 'infection'), ('recurrent disease', 'recurrent disease'), ('rejection', 'rejection')], max_length=100),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='graft_failure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='history_dsa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='i_dsa_mfi',
            field=models.IntegerField(blank=True, null=True, verbose_name='iDSA MFI'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='i_dsa_specificity',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('Cw', 'Cw'), ('DR', 'DR'), ('DQ', 'DQ'), ('DP', 'DP')], max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='immunodominant_dsa_class',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('I/II', 'I/II')], max_length=50),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='non_anti_hla_dsa',
            field=models.BooleanField(blank=True, null=True, verbose_name='non anti-HLA DSA'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='non_anti_hla_dsa_type',
            field=models.CharField(blank=True, choices=[('AT1R', 'AT1R'), ('MICA', 'MICA'), ('ECXM', 'ECXM'), ('vimentin', 'vimentin'), ('collagen', 'collagen'), ('K-a-1', 'K-a-1'), ('tubulin', 'tubulin')], max_length=100),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='percent_glomerulosclerosis',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='percent sclerotic glomeruli'),
        ),
        migrations.AddField(
            model_name='biopsy',
            name='preformed_dsa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='histology',
            name='ati',
            field=models.BooleanField(blank=True, null=True, verbose_name='Acute Tubular Injury (ATI)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='biopsy_assessment',
            field=models.CharField(blank=True, choices=[('frozen', 'frozen'), ('paraffin', 'paraffin'), ('electron microscopy', 'electron microscopy')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='histology',
            name='biopsy_method',
            field=models.CharField(blank=True, choices=[('core', 'core'), ('needle', 'needle'), ('wedge', 'wedge')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='histology',
            name='cg_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Glomerular Basement Membrane Double Contours (cg)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='g_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='glomerulitis (g)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='i_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='interstitial inflammation (i)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='num_arteries',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of arteries'),
        ),
        migrations.AddField(
            model_name='histology',
            name='num_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of cores'),
        ),
        migrations.AddField(
            model_name='histology',
            name='num_glomeruli',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of glomeruli'),
        ),
        migrations.AddField(
            model_name='histology',
            name='num_glomerulosclerosis',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of global glomerulosclerosis'),
        ),
        migrations.AddField(
            model_name='histology',
            name='num_sclerotic_glomeruli',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of segmentally sclerotic glomeruli'),
        ),
        migrations.AddField(
            model_name='histology',
            name='ptc_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='peritubular capillaritis (ptc)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='t_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='tubulitis (t)'),
        ),
        migrations.AddField(
            model_name='histology',
            name='tissue_technique',
            field=models.CharField(blank=True, choices=[('frozen', 'frozen'), ('paraffin', 'paraffin'), ('acidified formal alcohol', 'acidified formal alcohol (AFA')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='histology',
            name='tma',
            field=models.BooleanField(blank=True, null=True, verbose_name='Thrombotic Microangiopathy'),
        ),
        migrations.AddField(
            model_name='histology',
            name='v_score',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='intimal arteritis (v)'),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_proteinuria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transplant',
            name='donor_proteinuria_units',
            field=models.CharField(choices=[('g/g', 'g/g'), ('g/24h', 'g/24h'), ('mg/dL', 'mg/dL'), ('g/L', 'g/L'), ('mg/mmol', 'mg/mmol'), ('g/mmol', 'g/mmol')], default='g/g', max_length=50),
        ),
    ]
