# Generated by Django 3.2.10 on 2022-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistomxReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RCC_file', models.FileField(upload_to='')),
                ('render_pdf', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
